### PR TITLE
Add bz2 as requirement and catch only exceptions that will be handled

### PR DESCRIPTION
**Pull request by sascha-egerer**

### CODE REVIEW

**Comment by sascha-egerer** [comment]
The downloader need bz2 to extract the downloaded package. If bz2 is not available composer throws an exception witch is catched by the downloader and silently ignored. The Downloader just downloads every version and tries to extract it.

**Comment by jakoch** [comment]
Hey Sascha!

Ideally, the Composer `require` section would allow platform specific requirements, 
e.g. `require > linux > ext-bz2` (to express that ext-bz2 is only required on linux),
but unfortunately that isn't supported by Composer.

Thank you for contributing, especially for digging into the source and finding a silent exception.

Merging.

**Comment by sascha-egerer** [comment]
Thanks for merging. Will there be a release soon?

**Comment by jakoch** [comment]
I just tagged `2.1.1-p01`.
- https://github.com/jakoch/phantomjs-installer/releases/tag/2.1.1-p01
- https://packagist.org/packages/jakoch/phantomjs-installer#2.1.1-p01

**Pull request merged**
